#!/usr/bin/env python3
"""Capture Google auth cookies for google_maps_auth_mode=cookie."""

from __future__ import annotations

import argparse
import shlex
import stat
import sys
import time
from pathlib import Path
from typing import Dict, List, Tuple

from seleniumbase import Driver

COOKIE_CAPTURE_RULES: List[Tuple[str, bool, Tuple[str, ...]]] = [
    ("GOOGLE_MAPS_COOKIE_1PSID", True, ("1PSID", "__Secure-1PSID")),
    ("GOOGLE_MAPS_COOKIE_1PSIDTS", True, ("1PSIDTS", "__Secure-1PSIDTS")),
    ("GOOGLE_MAPS_COOKIE_SID", False, ("SID",)),
    ("GOOGLE_MAPS_COOKIE_HSID", False, ("HSID",)),
    ("GOOGLE_MAPS_COOKIE_SSID", False, ("SSID",)),
    ("GOOGLE_MAPS_COOKIE_SAPISID", False, ("SAPISID",)),
]


def _mask(value: str) -> str:
    if not value:
        return ""
    if len(value) <= 10:
        return "*" * len(value)
    return f"{value[:4]}...{value[-4:]}"


def _build_env_exports(cookies: Dict[str, str]) -> Tuple[List[str], List[str], Dict[str, str]]:
    lines: List[str] = []
    missing_required: List[str] = []
    chosen_sources: Dict[str, str] = {}
    for env_name, required, cookie_names in COOKIE_CAPTURE_RULES:
        value = ""
        source_name = ""
        for cookie_name in cookie_names:
            probe = cookies.get(cookie_name, "").strip()
            if probe:
                value = probe
                source_name = cookie_name
                break
        if value:
            lines.append(f"export {env_name}={shlex.quote(value)}")
            chosen_sources[env_name] = source_name
        elif required:
            missing_required.append(env_name)
    return lines, missing_required, chosen_sources


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Open a real browser, let you log in to Google Maps manually, then "
            "export cookie env vars used by this scraper."
        )
    )
    parser.add_argument(
        "--output",
        default=".env.google_maps.cookies",
        help="Output shell file with export lines (default: .env.google_maps.cookies)",
    )
    parser.add_argument(
        "--start-url",
        default="https://www.google.com/maps",
        help="URL to open first for manual login flow",
    )
    parser.add_argument(
        "--headless",
        action="store_true",
        help="Run browser in headless mode (not recommended for login flow)",
    )
    parser.add_argument(
        "--user-data-dir",
        default="",
        help="Optional Chrome user data dir to persist session across runs",
    )
    parser.add_argument(
        "--print-values",
        action="store_true",
        help="Print full cookie values to terminal (sensitive)",
    )
    parser.add_argument(
        "--show-cookie-names",
        action="store_true",
        help="Print discovered cookie names for debugging missing required cookies",
    )
    parser.add_argument(
        "--no-uc",
        action="store_true",
        help="Disable SeleniumBase UC mode",
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    output_path = Path(args.output).expanduser().resolve()

    driver_kwargs = {
        "uc": not args.no_uc,
        "headless": args.headless,
        "incognito": False,
    }
    if args.user_data_dir:
        driver_kwargs["user_data_dir"] = args.user_data_dir

    driver = None
    try:
        driver = Driver(**driver_kwargs)
        driver.get(args.start_url)

        print("\nManual step required:")
        print("1) Log in to Google in the opened browser window.")
        print("2) Complete any prompts/consent pages.")
        print("3) Make sure https://www.google.com/maps is loaded.")
        input("\nPress Enter here when done...")

        driver.get("https://www.google.com")
        time.sleep(1.0)

        raw_cookies = driver.get_cookies()
        cookies = {
            item.get("name", ""): item.get("value", "")
            for item in raw_cookies
            if item.get("name") and item.get("value")
        }
        exports, missing_required, chosen_sources = _build_env_exports(cookies)

        header = [
            "# Google Maps cookie env exports",
            "# Generated by tools/capture_google_maps_cookies.py",
            "# Keep this file private. Cookie values are sensitive credentials.",
            "",
        ]
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(header + exports) + "\n", encoding="utf-8")
        output_path.chmod(stat.S_IRUSR | stat.S_IWUSR)

        print(f"\nSaved {len(exports)} env vars to: {output_path}")
        print("Preview:")
        for env_name, _, _ in COOKIE_CAPTURE_RULES:
            line = next((l for l in exports if l.startswith(f"export {env_name}=")), None)
            if not line:
                print(f"  {env_name}=<missing>")
                continue
            value = line.split("=", 1)[1]
            shown = value if args.print_values else _mask(shlex.split(value)[0])
            source = chosen_sources.get(env_name, "")
            source_hint = f" (from {source})" if source else ""
            print(f"  {env_name}={shown}{source_hint}")

        if missing_required:
            print(
                "\nMissing required cookies: "
                + ", ".join(missing_required)
                + ". Login may not be complete or cookie scope is unavailable."
            )
            if args.show_cookie_names:
                names = ", ".join(sorted(cookies.keys()))
                print(f"Discovered cookie names: {names or '<none>'}")
            print("You can still source the file and test, but cookie mode may fail fast.")
            return 2

        print("\nNext:")
        print(f"  source {shlex.quote(str(output_path))}")
        print("  python3 start.py --google-maps-auth-mode cookie --fail-on-limited-view true")
        return 0
    except KeyboardInterrupt:
        print("\nCancelled.")
        return 130
    finally:
        if driver is not None:
            driver.quit()


if __name__ == "__main__":
    sys.exit(main())
